auth_app/urls.py
from django.urls import path
from . import views

# app name
app_name = "auth_app"


auth_patterns = [
    path('sign-up/', views.SignUpView.as_view(), name="sign_up"),
    path('sign-in/',views.SignInView.as_view(),name="sign_in"),
    path('logout/',views.LogOutView.as_view(),name="logout"),
]

quora_app/urls.py
from django.urls import path
from . import views

# app name
app_name = "quora_app"


# base pattern define
index_patterns = [
    path('', views.index, name="index"),
]

# questions pattern
questions_patterns = [
    path('post/view/',views.post_questions_view, name="post_questions_view"),
    path('post/create/',views.post_questions_create, name="post_questions_create"),
    path('post/update/<uuid:question_id>/',views.post_questions_update, name="post_questions_update"),
    path('post/delete/<uuid:question_id>/',views.post_questions_delete, name="post_questions_delete"),
]


# Answer patters
answers_patterns =[
    path('add/', views.answer_add, name="answer_add"),
    path('like/', views.like_answer, name="like"),
]

quora_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from auth_app.urls import auth_patterns
from quora_app.urls import questions_patterns, answers_patterns, index_patterns


urlpatterns = [
    path('admin/', admin.site.urls),

    # Index Page
    path('', include((index_patterns, 'quora_app'), namespace="index")),

    # Auth Patters
    path('auth/', include((auth_patterns, 'auth_app'))),

    # Questions Patterns
    path('questions/', include((questions_patterns, 'quora_app'), namespace="questions")),

    # Answer Patterns
    path('answers/', include((answers_patterns, 'quora_app'), namespace="answers")),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/custom.css' %}" rel="stylesheet">
    {% block css %}{% endblock %}

    <title>Quora</title>
  </head>
  <body style="background-color: rgb(241, 242, 242);">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
          <a class="navbar-brand" href="/">Quora</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav"> <!-- Use 'ms-auto' to align items to the right -->
                  <li class="nav-item">
                      <a class="nav-link" href="/">Home</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'questions:post_questions_create' %}">Post questions</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'questions:post_questions_view' %}">questions List</a>
                </li>
              </ul>
              <ul class="navbar-nav ms-auto">
                <div class="dropdown d-none d-md-block mt-1">
                  <button class="btn btn-success btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-lines-fill" viewBox="0 0 16 16">
                      <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm-5 6s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zM11 3.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5zm.5 2.5a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1h-4zm2 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1h-2zm0 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1h-2z"/>
                    </svg>
                    Profile
                  </button>
                  <ul class="dropdown-menu">
                    {% if user.is_authenticated %}
                      <li><a class="dropdown-item" href="javascript:void(0);">Profile</a></li>
                      <li><a class="dropdown-item" href="{% url 'auth_app:logout' %}">Logout</a></li>
                    {% else %}
                      <li><a class="dropdown-item" href="{% url 'auth_app:sign_up' %}">SignUp</a>
                      <li><a class="dropdown-item" href="{% url 'auth_app:sign_in' %}">SignIn</a>
                    {% endif %}
                  </ul>
                </div>
                {% if user.is_authenticated %}
                <li class="nav-item d-block d-md-none">
                  <a class="nav-link" href="javascript:void(0);">Profile</a>
                </li>
                <li class="nav-item d-block d-md-none">
                    <a class="nav-link" href="{% url 'auth_app:logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item d-block d-md-none">
                    <a class="nav-link" href="{% url 'auth_app:sign_up' %}">SignUp</a>
                </li>
                <li class="nav-item d-block d-md-none">
                    <a class="nav-link" href="{% url 'auth_app:sign_in' %}">SignIn</a>
                </li>
                {% endif %}
              </ul>
          </div>
      </div>
  </nav>
  
  
    {% block content %}{% endblock %}

    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}" ></script>
    
    {% block js %}{% endblock %}
  </body>
</html>

templates/message.html
{% load static %}
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">{{ message|safe }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}