auth_app/urls.py
from django.urls import path
from . import views

# app name
app_name = "auth_app"


auth_patterns = [
    path('sign-up/', views.SignUpView.as_view(), name="sign_up"),
    path('sign-in/',views.SignInView.as_view(),name="sign_in"),
    path('logout/',views.LogOutView.as_view(),name="logout"),
]

quora_app/urls.py
from django.urls import path
from . import views

# app name
app_name = "quora_app"


# base pattern define
index_patterns = [
    path('', views.index, name="index"),
]

# questions pattern
questions_patterns = [
    path('post/view/',views.post_questions_view, name="post_questions_view"),
    path('post/create/',views.post_questions_create, name="post_questions_create"),
    path('post/update/<uuid:question_id>/',views.post_questions_update, name="post_questions_update"),
    path('post/delete/<uuid:question_id>/',views.post_questions_delete, name="post_questions_delete"),
]


# Answer patters
answers_patterns =[
    path('add/', views.answer_add, name="answer_add"),
    path('like/', views.like_answer, name="like"),
]

quora_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from auth_app.urls import auth_patterns
from quora_app.urls import questions_patterns, answers_patterns, index_patterns


urlpatterns = [
    path('admin/', admin.site.urls),

    # Index Page
    path('', include((index_patterns, 'quora_app'), namespace="index")),

    # Auth Patters
    path('auth/', include((auth_patterns, 'auth_app'))),

    # Questions Patterns
    path('questions/', include((questions_patterns, 'quora_app'), namespace="questions")),

    # Answer Patterns
    path('answers/', include((answers_patterns, 'quora_app'), namespace="answers")),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

quora_app/models.py
from django.db import models
from auth_app.models import User
from common.models import TimeStampMixin
import uuid

# Create your models here.
class Questions(TimeStampMixin):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=200)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='questions/')
    visable = models.BooleanField(default=True)

class Answers(TimeStampMixin):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    content = models.TextField()
    question = models.ForeignKey(Questions, 
        on_delete=models.CASCADE, 
        related_name="answers"
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    visable = models.BooleanField(default=True)

    class Meta:
        unique_together = ("author", "question")


class Likes(TimeStampMixin):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    answer = models.ForeignKey(Answers, 
        on_delete=models.CASCADE, 
        related_name="likes"
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("author", "answer")

quora_app/forms.py
from django import forms
from .models import Questions, Answers
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class QuestionsForm(forms.ModelForm):
    '''
        while create and update Question this form is managed.
    '''
    class Meta:
        model = Questions
        fields = ('title', 'content', 'visable', 'image')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control', 'accept':'image/*'}),
        }

    def clean_image(self):
        image = self.cleaned_data.get('image')
        if image:
            # Check the file extension
            valid_extensions = ['jpg', 'jpeg', 'png', 'gif']
            print(image.name.split('.')[-1].lower())
            extension = image.name.split('.')[-1].lower()
            if extension not in valid_extensions:
                raise ValidationError(_('Invalid file format. Only JPG, JPEG, PNG, and GIF images are allowed.'))
        return image

quora_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from quora_app import models, forms
from django.contrib import messages
from django.urls import reverse
from django.http import JsonResponse

# Create your views here.

def index(request):
    questions_obj = models.Questions.objects.all().order_by('-updated_at')
    count = len(questions_obj)
    return render(request,'quora_app/index.html', 
        {'questions_obj': questions_obj, 'count': count})


@login_required
def post_questions_create(request):
    form = forms.QuestionsForm()
    if request.method == 'POST':
        form = forms.QuestionsForm(request.POST, request.FILES)
        if form.is_valid():
            form_obj = form.save(commit=False)
            form_obj.author = request.user
            form_obj.save()
            messages.success(request, f'Post added Successful !' )
            return redirect('questions:post_questions_view')
    context ={"form" : form}
    return render(request, 'quora_app/questions/post_create.html', context)


@login_required
def post_questions_update(request, question_id):
    question_obj = get_object_or_404(models.Questions, id=question_id)
    form = forms.QuestionsForm(instance=question_obj)
    if request.method == 'POST':
        form = forms.QuestionsForm(request.POST, request.FILES, instance=question_obj)
        if form.is_valid():
            form_obj = form.save()
            messages.success(request, f'Post Updated Successful !' )
            return redirect('questions:post_questions_view')
    context ={"form" : form, 'question_obj':question_obj}
    return render(request, 'quora_app/questions/post_create.html', context)


@login_required
def post_questions_delete(request, question_id):
    question_obj = models.Questions.objects.filter(
        id = question_id, author = request.user)

    if question_obj:
        question_obj.delete()
        messages.success(request, f'Post Deleted Successful !' )
    else:
        messages.error(request, f'Object not Found !' )
    return redirect('questions:post_questions_view')


@login_required
def post_questions_view(request):
    questions_obj = models.Questions.objects.filter(author=request.user)
    context={'questions_obj': questions_obj} 
    return render(request, 'quora_app/questions/post_view.html', context)


@login_required
def answer_add(request):
    if request.method == 'POST':
        question_reference = request.POST.get('question_reference')
        content = request.POST.get('content')

        questions_obj = get_object_or_404(models.Questions, id=question_reference)
        obj, created = models.Answers.objects.update_or_create(
            question=questions_obj, author=request.user )
        obj.content = content
        obj.save()

        if created:
            messages.success(request, f'Answer is Submitted successfully.')
        else:
            messages.success(request, f'Answer is Updated successfully.')

        url_with_fragment = f"{reverse('index:index')}#post_id_{questions_obj.id}"
        return redirect(url_with_fragment)
    
@login_required
def like_answer(request):
    if request.method == 'POST':
        print('enter hear in post')
        answer_id = request.POST.get('answer_id')
        answers_obj = get_object_or_404(models.Answers, id=answer_id)
        obj, created = models.Likes.objects.update_or_create(
            answer=answers_obj, author=request.user )
        obj.save()
        if obj:
            data = {
                'status': 'success',
                'message': 'Like added successfully.',
                'likes_count': 1 }
        else:
            data = {
                'status': 'error',
                'message': 'Failed to like the post.'}

        return JsonResponse(data)
    return JsonResponse({'status': 'error', 'message': 'Invalid request.'})

quora_app/templates/quora_app/questions/post_create.html
{% extends 'base.html' %}
{% load static %}
{% block css %}{% endblock %}
{% block content %}
{% include 'message.html' %}
  <div class="container">
    <div class="row">
      <div class="col-12 col-lg-12">
        <ol class="breadcrumb bg-transparent float-end pt-3 mb-0 px-0">
            <li class="breadcrumb-item text-secondary"><a href="/" class="text-decoration-none">Home</a></li>
            <li class="breadcrumb-item active">Questions {% if '/post/create/' in request.path %}Create {% else %}Update{% endif %}</li>
        </ol>
      </div>
      <div class="col-12">
        <h2 class="d-inline-block">Questions {% if '/post/create/' in request.path %}Create {% else %}Update{% endif %}</h2>
        <p>{% if '/post/create/' in request.path %}Create {% else %}Update{% endif %} the Questions post for below.</p>
      </div>
      <div class="col-12 col-md-8 mb-5">
        <form method="post" enctype="multipart/form-data" class="row g-3 needs-validation border p-4 rounded" novalidate="">
           {% csrf_token %}
           
           {% include 'auth_app/forms/auth_widget.html' %}

            <div calss="col-12">
                <a href="/" class="btn btn-danger">Back</a>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

quora_app/templates/quora_app/questions/post_view.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link href="{% static 'assets/css/custom.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
{% include 'message.html' %}
<div class="container">
  <div class="row">
    <div class="col-12 col-lg-12">
      <ol class="breadcrumb bg-transparent float-end pt-3 mb-0 px-0">
        <li class="breadcrumb-item text-secondary"><a href="/" class="text-decoration-none">Home</a></li>
        <li class="breadcrumb-item active">Questions View</li>
      </ol>
    </div>
    <div class="col-12 mb-4">
        <div class="row">
            <div class="col-sm-10">
                <h2 class="d-inline-block">Questions View</h2>
                <p>You can see all the posted questions here.</p>
            </div>
            <div class="col-sm-2 d-flex justify-content-end align-items-center">
                <a class="btn btn-success" href="{% url 'questions:post_questions_create' %}">Add Questions</a>  
            </div>
        </div>
    </div>
    <div class="col-12 col-md-8 mb-5">
        {% if questions_obj %}
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                    <th scope="col">Sr No</th>
                    <th scope="col">Title</th>
                    <th scope="col">Visible</th>
                    <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                        {% for question in questions_obj %}
                        <tr>
                            <th scope="row">{{forloop.counter}}</th>
                            <td>{{question.title|truncatewords:6}}</td>
                            <td>
                                {% if question.visable %}
                                    <a href="javascript:void(0);" class="text-success">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="30" fill="currentColor" class="bi bi-check" viewBox="0 0 16 16">
                                            <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                                        </svg>
                                    </a>
                                {% else %}
                                    <a href="javascript:void(0);" class="text-danger">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="30" fill="currentColor" class="bi bi-x" viewBox="0 0 16 16">
                                            <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                        </svg>
                                    </a>
                                {% endif %}

                            </td>
                            <td>
                                <a href="{% url 'index:index' %}#post_id_{{ question.id }}" class="btn btn-info btn-sm my-1">View</a>
                                <a href="{% url 'questions:post_questions_update' question.id %}" class="btn btn-primary btn-sm my-1">Edit</a>
                                <a href="{% url 'questions:post_questions_delete' question.id %}" class="btn btn-danger btn-sm my-1">Delete</a>
                            </td>
                        </tr>
                        {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <div class="col-sm-12">
            <div class="alert alert-warning fade show" role="alert">
                No Questions Found!
              </div>
        </div>
        {% endif %}
    </div>
  </div>
</div>
{% endblock %}